return {
	{
		"folke/which-key.nvim",
		event = "VeryLazy",
		config = function()
			local wk = require("which-key")
			local utils = require("config.utils")
			return wk.add({
				{ "<leader>s", group = "Search" },
				{ "<leader>sf", "<cmd>Telescope find_files<cr>", desc = "Find Files (all)" },
				{ "<leader>sr", "<cmd>GrugFar<cr>", desc = "Replace" },
				{ "<leader>sR", "<cmd>Telescope resume<cr>", desc = "Resume previous search" },
				{ "<leader>st", "<cmd>Telescope lsp_type_definitions<cr>", desc = "Type definitions" },
				{ "<leader>si", "<cmd>Telescope lsp_implementations<cr>", desc = "Implementations" },
				{ "<leader>sg", "<cmd>Telescope git_files<cr>", desc = "Git Files" },
				{ "<leader>ss", "<cmd>Telescope live_grep<cr>", desc = "String" },
				{ "<leader>sm", "<cmd>Telescope marks<cr>", desc = "Marks" },
				{ "<leader>sb", "<cmd>Telescope buffers<cr>", desc = "Buffers" },
				{ "<leader>su", "<cmd>Telescope undo<cr>", desc = "Undo" },
				{ "<leader>so", "<cmd>Telescope oldfiles<cr>", desc = "Oldfiles" },
				{ "<leader>sh", "<cmd>Telescope help_tags<cr>", desc = "Help" },
				{ "<leader>sj", "<cmd>Telescope jumplist<cr>", desc = "Jumplist" },
				{ "<leader>f", group = "Files" },
				{ "<leader>fo", "<cmd>Oil<cr>", desc = "Oil" },
				{ "<leader>fe", "<cmd>NvimTreeFindFileToggle<cr>", desc = "Explorer" },
				{ "<leader>t", group = "Tasks" },
				{ "<leader>tt", "<cmd>OverseerToggle<cr>", desc = "Toggle tasks list" },
				{ "<leader>tr", "<cmd>OverseerRun<cr>", desc = "Run task" },
				{ "<leader>ti", "<cmd>OverseerInfo<cr>", desc = "Info" },
				{ "<leader>g", group = "Git" },
				{ "<leader>gg", "<cmd>Neogit<cr>", desc = "Git" },
				{ "<leader>gb", "<cmd>BlameToggle<cr>", desc = "Blame" },
				{ "<leader>gs", "<cmd>Telescope git_status<cr>", desc = "Status" },
				{ "<leader>gd", desc = "Diff" },
				{ "<leader>gdd", "<cmd>DiffviewOpen<cr>", desc = "Diff with current Index" },
				{ "<leader>gdh", "<cmd>DiffviewFileHistory %<cr>", desc = "Diff file history" },
				{ "<leader>gdc", "<cmd>DiffviewClose<cr>", desc = "Close Diffview" },
				{ "<leader>gc", desc = "Conflicts" },
				{ "<leader>gcc", "<cmd>Telescope conflicts<cr>", desc = "List conflicts" },
				{ "<leader>gco", "<cmd>GitConflictChooseOurs<cr>", desc = "Choose ours" },
				{ "<leader>gct", "<cmd>GitConflictChooseTheirs<cr>", desc = "Choose theirs" },
				{ "<leader>gcb", "<cmd>GitConflictChooseBoth<cr>", desc = "Choose both" },
				{ "<leader>gcn", "<cmd>GitConflictChooseNone<cr>", desc = "Choose none" },
				{ "<leader>c", group = "Quickfix list" },
				{ "<leader>ct", "<cmd>Trouble qflist toggle<cr>", desc = "Quickfix list (Trouble)" },
				{ "<leader>co", "<cmd>copen<cr>", desc = "Open" },
				{ "<leader>cc", "<cmd>cclose<cr>", desc = "Close" },
				{ "<leader>cn", "<cmd>cnext<cr>", desc = "Next" },
				{ "<leader>cp", "<cmd>cprev<cr>", desc = "Prev" },
				{ "<leader>l", group = "LSP" },
				{ "<leader>lI", "<cmd>Mason<cr>", desc = "Install" },
				{
					"<leader>ll",
					"<cmd>Trouble lsp toggle<cr>",
					desc = "LSP definitions / references / ... (Trouble)",
				},
				{ "<leader>ld", "<cmd>lua vim.lsp.buf.definition()<cr>", desc = "Definiion" },
				{ "<leader>li", "<cmd>lua vim.lsp.buf.implementation()<cr>", desc = "Implementation" },
				{ "<leader>lh", "<cmd>lua vim.lsp.buf.hover()<cr>", desc = "Signature" },
				{ "<leader>la", "<cmd>lua vim.lsp.buf.code_action()<cr>", desc = "Actions" },
				{ "<leader>lr", "<cmd>lua vim.lsp.buf.references()<cr>", desc = "References" },
				{ "<leader>lR", "<cmd>lua vim.lsp.buf.rename()<cr>", desc = "Rename" },
				{
					"<leader>lf",
					"<cmd>lua require('conform').format(( async = true, lsp_fallback = true ))<cr>",
					desc = "Format",
				},
				{ "<leader>d", group = "Diagnostics" },
				{ "<leader>dt", "<cmd>Trouble diagnostics toggle<cr>", desc = "Trouble" },
				{ "<leader>dT", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", desc = "Trouble (current file)" },
				{ "<leader>ds", "<cmd>Trouble symbols toggle focus=false<cr>", desc = "Symbols" },
				{ "<leader>dh", "<cmd>lua vim.diagnostic.open_float()<cr>", desc = "Open highlighted" },
				{ "<leader>dn", "<cmd>lua vim.diagnostic.goto_next()<cr>", desc = "Next" },
				{ "<leader>dp", "<cmd>lua vim.diagnostic.goto_prev()<cr>", desc = "Previous" },
				{ "<leader>.", "<cmd>e ~/.config/nvim<cr>", desc = "Edit config" },
				{ "<leader>v", group = "View" },
				{ "<leader>vz", "<cmd>ZenMode<cr>", desc = "Zen mode" },
				{ "<leader>vm", "<cmd>Markview toggle<cr>", desc = "Markdown view" },
				{ "<leader>vM", "<cmd>Markview splitToggle<cr>", desc = "Markdown view (split)" },
				{ "<leader>u", group = "Utils" },
				{
					"<leader>uc",
					utils.copyFilepath,
					desc = "Copy filepath to clipboard",
				},
				{ "<leader>us", "<cmd>ISwapWith<cr>", desc = "Swap arguments" },
				{ "<leader>ul", group = "Logs" },
				{ "<leader>ulv", "<cmd>Chainsaw variableLog<cr>", desc = "Log variable" },
				{ "<leader>uls", "<cmd>Chainsaw stacktraceLog<cr>", desc = "Log stacktrace" },
				{ "<leader>ulo", "<cmd>Chainsaw objectLog<cr>", desc = "Log object" },
				{ "<leader>ulc", "<cmd>Chainsaw clearLog<cr>", desc = "Clear log" },
				{ "<leader>ulr", "<cmd>Chainsaw removeLogs<cr>", desc = "Remove logs" },
			})
		end,
	},
}
